
version: '3.7'
services:
  postgres:
    image: postgres:13.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres 
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  
  app:
    build:
      context: ./
      dockerfile: Dockerfile.pnpm
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=http://localhost:5432
    volumes:
      - ./:/app
      - /app/node_modules
